source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘8.0’
#use_frameworks!
inhibit_all_warnings!

def install_pods
    pod 'AFNetworking', '~> 3.1.0'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'Masonry', '~> 1.0.2'
    pod 'QMUIKit', '~> 1.6.0'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    pod 'XRCarouselView', '~> 2.5.6'
end


target 'OFProjectTemplate' do
  install_pods
end
